export { AppScene } from '@/components/patterns'
export { ConsolePageTemplate } from './console-page-template'
export { WorkspacePageTemplate } from './workspace-page-template'
export { StudioPageTemplate } from './studio-page-template'
export { StudioTriPanePageTemplate } from './studio-tri-pane-page-template'
export { SplitDetailPageTemplate } from './split-detail-page-template'
