import { tailwindColors } from './tailwind-vars'

// Keep generated files below the source size limit without duplicating the
// runtime light/dark values. Inline utilities read the scoped runtime tokens.
export function generateTailwindThemeFiles(): Record<string, string> {
  const entries = Object.entries(tailwindColors).sort(([a], [b]) =>
    a.localeCompare(b, 'en'),
  )
  return Object.fromEntries(
    Array.from({ length: Math.ceil(entries.length / 250) }, (_, index) => {
      const declarations = entries
        .slice(index * 250, (index + 1) * 250)
        .map(([name, value]) => `  --color-${name}: ${value};`)
        .join('\n')
      return [
        `tailwind-tokens-${index + 1}.generated.css`,
        `/* Generated by npm run build:themes; do not edit. */\n@theme inline {\n${declarations}\n}\n`,
      ]
    }),
  )
}
