import { Operator } from './constant'
import {
  Bot,
  Code,
  Database,
  FileCode,
  FileText,
  Filter,
  GitBranch,
  Globe,
  GalleryVerticalEnd,
  HousePlus,
  Infinity as InfinityIcon,
  Layers,
  List,
  ListTree,
  LogOut,
  Mail,
  MessageSquare,
  NotebookPen,
  Repeat,
  Replace,
  Search,
  Settings2,
  StickyNote,
  Type,
  Variable,
  Wrench,
} from 'lucide-react'

export const OperatorIconFontMap: Record<string, string> = {
  [Operator.Retrieval]: 'KR',
  [Operator.Categorize]: 'a-QuestionClassification',
  [Operator.Message]: 'reply',
  [Operator.A2UI]: 'card',
  [Operator.Iteration]: 'loop',
  [Operator.Switch]: 'condition',
  [Operator.Code]: 'code-set',
  [Operator.Agent]: 'agent-ai',
  [Operator.UserFillUp]: 'await',
  [Operator.StringTransform]: 'a-textprocessing',
  [Operator.Note]: 'notebook-pen',
  [Operator.ExeSQL]: 'executesql-0',
  [Operator.Invoke]: 'httprequest-0',
  [Operator.Email]: 'sendemail-0',
  [Operator.ListOperations]: 'a-listoperations',
  [Operator.VariableAssigner]: 'a-ariableassigner',
  [Operator.VariableAggregator]: 'aggregator',
}

export const LucideIconMap: Record<string, typeof Bot> = {
  [Operator.Begin]: HousePlus,
  [Operator.Retrieval]: Database,
  [Operator.Message]: MessageSquare,
  [Operator.A2UI]: GalleryVerticalEnd,
  [Operator.Categorize]: GitBranch,
  [Operator.Switch]: GitBranch,
  [Operator.Relevant]: GitBranch,
  [Operator.RewriteQuestion]: Replace,
  [Operator.KeywordExtract]: Type,
  [Operator.Agent]: Bot,
  [Operator.Tool]: Wrench,
  [Operator.Note]: NotebookPen,
  [Operator.Placeholder]: StickyNote,
  [Operator.Iteration]: Repeat,
  [Operator.IterationStart]: Repeat,
  [Operator.Code]: Code,
  [Operator.DuckDuckGo]: Search,
  [Operator.Wikipedia]: Globe,
  [Operator.PubMed]: FileText,
  [Operator.ArXiv]: FileText,
  [Operator.Google]: Search,
  [Operator.Bing]: Search,
  [Operator.GoogleScholar]: Search,
  [Operator.GitHub]: Code,
  [Operator.SearXNG]: Search,
  [Operator.TavilySearch]: Search,
  [Operator.TavilyExtract]: FileText,
  [Operator.WenCai]: Search,
  [Operator.YahooFinance]: Settings2,
  [Operator.ExeSQL]: Database,
  [Operator.Crawler]: Globe,
  [Operator.Invoke]: Globe,
  [Operator.Email]: Mail,
  [Operator.UserFillUp]: MessageSquare,
  [Operator.StringTransform]: Type,
  [Operator.PDFGenerator]: FileText,
  [Operator.DataOperations]: FileCode,
  [Operator.ListOperations]: List,
  [Operator.VariableAssigner]: Variable,
  [Operator.VariableAggregator]: Layers,
  [Operator.Loop]: InfinityIcon,
  [Operator.LoopStart]: InfinityIcon,
  [Operator.ExitLoop]: LogOut,
  [Operator.File]: FileText,
  [Operator.Parser]: FileCode,
  [Operator.Tokenizer]: Type,
  [Operator.Splitter]: ListTree,
  [Operator.HierarchicalMerger]: Layers,
  [Operator.Extractor]: Filter,
}
