export const SLIDER_PRESETS = {
  temperature: {
    label: 'Temperature',
    tooltip: '控制输出的随机性，值越高越有创意',
    min: 0,
    max: 2,
    step: 0.01,
    default: 0.5,
    precision: 2,
  },
  topP: {
    label: 'Top P',
    tooltip: '核采样参数，控制输出的多样性',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.85,
    precision: 2,
  },
  presencePenalty: {
    label: 'Presence Penalty',
    tooltip: '降低重复主题的可能性',
    min: 0,
    max: 2,
    step: 0.01,
    default: 0.2,
    precision: 2,
  },
  frequencyPenalty: {
    label: 'Frequency Penalty',
    tooltip: '降低重复用词的可能性',
    min: 0,
    max: 2,
    step: 0.01,
    default: 0.3,
    precision: 2,
  },
  maxTokens: {
    label: 'Max Tokens',
    tooltip: '限制单次回复的最大 token 数量',
    min: 1,
    max: 128000,
    step: 1,
    default: 4096,
    inputOnly: true,
    inputWidth: 100,
    precision: 0,
  },
} as const
